import Link from 'next/link';

export const metadata = {
  title: 'Meu App com Layout',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <header style={{ 
            backgroundColor: '#f0f0f0', 
            padding: '1rem', 
            marginBottom: '1rem', 
            borderBottom: '1px solid #ccc' 
        }}>
          <nav>
            <Link href="/" style={{ marginRight: '15px' }}>Home</Link>
            <Link href="/novarota">Nova Rota</Link>
          </nav>
        </header>

        <main>
          {children}
        </main>
        
      </body>
    </html>
  )
}